name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, bugfix/*, feature/* ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  GO_VERSION: '1.21'
  DOCKER_IMAGE: ${{ github.repository }}

jobs:
  lint:
    name: Lint and format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.2

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Check formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Code is not formatted. Please run 'gofmt -w .' to format your code.";
            gofmt -1 .
            exit 1;
          fi

  test:
    name: Run tests
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.20, 1.21 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: ${{ matrix.go-version }}

        - name: Install dependencies
          run: go mod download

        - name: Run tests
          run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v3
          with:
            files: ./coverage.txt
            fail_ci_if_error: true

  security:
    name: Security scan
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: ./...

  build:
    name: Build and Push Docker Image
    needs: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags:
            commit_of_the_day:latest