name: Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - 'src/**'
      - 'go.mod'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - 'src/**'
      - 'go.mod'
  workflow_dispatch:

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install godoc
        run: go install golang.org/x/tools/cmd/godoc@latest

      - name: Generate API Documentation
        run: |
          mkdir -p docs/api
          godoc -http=:6060 &
          sleep 5
          wget -r -np -k -p http://localhost:6060/pkg/your/module/path/ -P docs/api
          pkill godoc

      - name: Check for dead links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          folder-path: 'docs'

  deploy-docs:
    name: Deploy Documentation
    needs: generate-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          commit_message: 'docs: update documentation'

  validate-docs:
    name: Validate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Markdown formatting
        uses: DavidAnson/markdownlint-action@v1
        with:
          config: .github/markdownlint.json

      - name: Check for broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          folder-path: 'docs'
      
      - name: Check spelling
        uses: rojopolis/spellcheck-github-action@v0.19.0
        with:
          source_files: 'docs/**/*.md'
          task_name: 'Spell Check Documentation'
          use_gitignore: 'true'
          use_ignore_words_list: 'true'
          ignore_words_list: '.spellcheck-ignore-words.txt'
